# Generated by Django 2.2.10 on 2021-07-29 05:36

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.TextField(blank=True)),
                ('telefone', models.TextField(blank=True)),
                ('acesso', models.BooleanField(default=False)),
                ('financeiro', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.TextField(unique=True)),
                ('nome', models.TextField()),
                ('dataNascimento', models.DateField()),
                ('sexo', models.CharField(blank=True, max_length=12, null=True)),
                ('telefone', models.TextField()),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('grupoSocial', models.CharField(blank=True, max_length=50, null=True)),
                ('escolaridade', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=50, null=True)),
                ('areaImovel', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('areaPropria', models.CharField(blank=True, max_length=4, null=True)),
                ('zonaMoradia', models.CharField(blank=True, max_length=50, null=True)),
                ('formaAcessoAguaRio', models.BooleanField(default=False)),
                ('formaAcessoAguaAcude', models.BooleanField(default=False)),
                ('formaAcessoAguaPoco', models.BooleanField(default=False)),
                ('formaAcessoAguaCisterna', models.BooleanField(default=False)),
                ('formaAcessoAguaOutrasFormas', models.BooleanField(default=False)),
                ('atividadeProdutivaAgricultura', models.BooleanField(default=False)),
                ('atividadeProdutivaPecuaria', models.BooleanField(default=False)),
                ('atividadeProdutivaOutros', models.BooleanField(default=False)),
                ('principaisProdutos', models.TextField(blank=True, null=True)),
                ('comercializacaoProducaoComercioLocal', models.BooleanField(default=False)),
                ('comercializacaoProducaoCooperativa', models.BooleanField(default=False)),
                ('comercializacaoProducaoFeira', models.BooleanField(default=False)),
                ('comercializacaoProducaoDiretaConsumidor', models.BooleanField(default=False)),
                ('estimativaRendaAnual', models.CharField(blank=True, max_length=50, null=True)),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=50, null=True)),
                ('nome', models.CharField(max_length=50)),
                ('grauParentesco', models.CharField(max_length=50)),
                ('dataNascimento', models.DateField()),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='app.Familia')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['id'],
            },
        ),
    ]
